
#: import icon iconfonts.icon
# Custom button
<CustButton@ToggleButton>:
    font_size: 25
    size: 45,45
    text: ""
    background_color: .68,.68,.84,1

<CustToggleButton@ToggleButton>:
    font_size: 25
    font_name:"Calibri"
    background_color: .68,.68,.84,1

<CustButton2@Button>:
    font_size: 15
   
    size: 46,45
    text: ""

<CustButton4@ToggleButton>:
    font_size: 15
   
    size: 46,45
    text: ""

<CustButton3@Button>:
    font_size: 18
    size: 45,35

    

<Manager>:
    id: screen_manager
    screen_one:screen_one
    screen_two:screen_two
    screen_three:screen_three

    SeqScreen:
        id:screen_one
        name:'piano_roll'
        manager: screen_manager


    SongScreen:
        id:screen_two 
        name: 'song_mode'
        manager: screen_manager

    ParamScreen:
        id:screen_three 
        name: 'param_mode'
        manager: screen_manager

    SaveSeq:
        id:screen_four
        name: 'SaveSeq'
        manager: screen_manager

    LoadSeq:
        id:screen_five
        name: 'LoadSeq'
        manager: screen_manager

    SaveSeq:
        id:screen_six
        name: 'SaveSong'
        manager: screen_manager

    SaveSeq:
        id:screen_seven
        name: 'LoadSong'
        manager: screen_manager

    LFOScreen:
        id:screen_eight
        name: 'LFOScreen'
        manager: screen_manager


    ADSRScreen:
        id:screen_nine
        name: 'ADSRScreen'
        manager: screen_manager


<LoadSeq>
    id: loadseq
    b007:b007
    b5001:b5001
    b5002:b5002
    b5003:b5003
    b5004:b5004
    b5005:b5005
    b5006:b5006
    b5007:b5007
    b5008:b5008
    b5009:b5009
    b5010:b5010
    b5011:b5011
    b5012:b5012
    b5013:b5013
    b5014:b5014
    b5015:b5015
    b5016:b5016
    b001:b001
    b002:b002
    
    GridLayout:
        canvas.before:
            Color:
                rgba: (.37, .39, .45, 0.4)
            Rectangle:
                pos: self.pos
                size: self.size

        CustButton3:
            pos: 648,419
            size: 150, 60
            text: "CLOSE"
            id:b007
            on_press:root.manager.current='piano_roll'
            on_press: loadseq.leaving()            
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1

        CustButton3:
            pos: 139,236
            size: 130,67
            text: "01"
            id:b5001
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(1)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 269,236
            size: 130,67
            text: "02"
            id:b5002
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(2)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 399,236
            size: 130,67
            text: "03"
            id:b5003
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(3)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 529,236
            size: 130,67
            text: "04"
            id:b5004
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(4)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 139,168
            size: 130,67
            text: "05"
            id:b5005
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(5)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 269,168
            size: 130,67
            text: "06"
            id:b5006
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(6)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 399,168
            size: 130,67
            text: "07"
            id:b5007
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(7)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 529,168
            size: 130,67
            text: "08"
            id:b5008
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(8)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 139,100
            size: 130,67
            text: "09"
            id:b5009
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(9)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 269,100
            size: 130,67
            text: "10"
            id:b5010
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(10)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 399,100
            size: 130,67
            text: "11"
            id:b5011
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(11)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 529,100
            size: 130,67
            text: "12"
            id:b5012
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(12)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 139,32
            size: 130,67
            text: "13"
            id:b5013
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(13)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 269,32
            size: 130,67
            text: "14"
            id:b5014
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(14)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 399,32
            size: 130,67
            text: "15"
            id:b5015
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(15)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 529,32
            size: 130,67
            text: "16"
            id:b5016
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:loadseq.choice(16)
            on_press:root.manager.current='piano_roll'

        CustToggleButton:
            id:b001
            pos: 190,330
            size: 200,60
            text: "INTERNAL"
            state: "down"
            on_press: b002.state="normal"
            on_press: b001.state="down"

        CustToggleButton:
            markup: True
            id:b002
            pos: 410,330
            size: 200,60
            text: "IMPORT"
            on_press: b001.state="normal"
            on_press: b002.state="down"
        Label:
            pos: 350,385
            font_size:28
            text:"Loading Sequence:"
        CustButton3:
            text:"up"
            pos: 1010,50
            on_press:loadseq.up()
        CustButton3:
            text:"dw"
            pos: 1010,10
            on_press:loadseq.dw()




<SaveSeq>
    id: saveseq
    b007:b007
    b5001:b5001
    b5002:b5002
    b5003:b5003
    b5004:b5004
    b5005:b5005
    b5006:b5006
    b5007:b5007
    b5008:b5008
    b5009:b5009
    b5010:b5010
    b5011:b5011
    b5012:b5012
    b5013:b5013
    b5014:b5014
    b5015:b5015
    b5016:b5016
    b001:b001
    b002:b002
    
    GridLayout:
        canvas.before:
            Color:
                rgba: (.37, .39, .45, 0.4)
            Rectangle:
                pos: self.pos
                size: self.size

        CustButton3:
            pos: 648,419
            size: 150, 60
            text: "CLOSE"
            id:b007
            on_press:root.manager.current='piano_roll'
            on_press: saveseq.leaving()             
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1

        CustButton3:
            pos: 139,236
            size: 130,67
            text: "01"
            id:b5001
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(1)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 269,236
            size: 130,67
            text: "02"
            id:b5002
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(2)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 399,236
            size: 130,67
            text: "03"
            id:b5003
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(3)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 529,236
            size: 130,67
            text: "04"
            id:b5004
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(4)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 139,168
            size: 130,67
            text: "05"
            id:b5005
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(5)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 269,168
            size: 130,67
            text: "06"
            id:b5006
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(6)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 399,168
            size: 130,67
            text: "07"
            id:b5007
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(7)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 529,168
            size: 130,67
            text: "08"
            id:b5008
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(8)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 139,100
            size: 130,67
            text: "09"
            id:b5009
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(9)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 269,100
            size: 130,67
            text: "10"
            id:b5010
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(10)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 399,100
            size: 130,67
            text: "11"
            id:b5011
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(11)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 529,100
            size: 130,67
            text: "12"
            id:b5012
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(12)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 139,32
            size: 130,67
            text: "13"
            id:b5013
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(13)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 269,32
            size: 130,67
            text: "14"
            id:b5014
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(14)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 399,32
            size: 130,67
            text: "15"
            id:b5015
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(15)
            on_press:root.manager.current='piano_roll'
        CustButton3:
            pos: 529,32
            size: 130,67
            text: "16"
            id:b5016
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:saveseq.choice(16)
            on_press:root.manager.current='piano_roll'

        CustToggleButton:
            id:b001
            pos: 190,330
            size: 200,60
            text: "INTERNAL"
            state: "down"
            on_press: b002.state="normal"
            on_press: b001.state="down"

        CustToggleButton:
            markup: True
            id:b002
            pos: 410,330
            size: 200,60
            text: "EXPORT %s"%(icon('icon-lock', 22))
            on_press: b001.state="normal"
            on_press: b002.state="down"

        Label:
            pos: 350,385
            font_size:28
            text:"Saving Sequence:"
        CustButton3:
            text:"up"
            pos: 1010,50
            on_press:saveseq.up()
        CustButton3:
            text:"dw"
            pos: 1010,10
            on_press:saveseq.dw()

            










<ParamScreen>
    id: pmode
    b1001:b1001
    b1002:b1002
    b1003:b1003
    b1004:b1004
    b1005:b1005
    b1006:b1006
    b2001:b2001
    b2002:b2002
    b2003:b2003
    b2004:b2004
    b2005:b2005
    b2006:b2006
    b2007:b2007
    b2008:b2008
    b4000:b4000
    b4001:b4001
    b4002:b4002
    b4003:b4003
    b3005:b3005
    b5000:b5000
    b5001:b5001
    b5002:b5002
    b5003:b5003
    b5004:b5004
    b5005:b5005
    b5006:b5006
    b5007:b5007
    b5008:b5008
    b5009:b5009
    b5010:b5010
    b5011:b5011
    b5012:b5012
    b5013:b5013
    b5014:b5014
    b5015:b5015
    b5016:b5016
    b5017:b5017
    lbl1:lbl1
    lbl2:lbl2
    lbl3:lbl3
    lbl4:lbl4
    lbl5:lbl5
    lbl6:lbl6
    b10001:b10001
    b10002:b10002
    b10003:b10003
    b10004:b10004
    b10005:b10005
    b10006:b10006
    b20001:b20001
    b20002:b20002
    b20003:b20003
    b20004:b20004
    b20005:b20005
    b20006:b20006
    b20007:b20007
    b20008:b20008
    b30001:b30001
    b30002:b30002
    b30003:b30003
    b30004:b30004
    b30005:b30005
    b30006:b30006
    lbl10:lbl10
    lbl20:lbl20
    lbl30:lbl30
    lbl40:lbl40
    lbl50:lbl50
    lbl60:lbl60
    b100002:b100002
    b100003:b100003
    b100001:b100001
    b1000001:b1000001
    b1000002:b1000002
    b1000003:b1000003
    b100004:b100004
    b100005:b100005
    b100006:b100006
    b1000004:b1000004
    b1000005:b1000005
    b000000001:b000000001

    GridLayout:
        canvas.before:
            Color:
                rgba: (.37, .39, .45, 0.4)
            Rectangle:
                pos: self.pos
                size: self.size

    TabbedPanel:
        id:b000000001
        do_default_tab:False
        tab_height:57
        tab_width:150
        
        TabbedPanelItem:
            on_press:pmode.closemenu()
            text:'MIDI'
            background_color :.68,.68,.84,1
            font_size: 25
            font_name:"Calibri"
            size: 150, 60

            GridLayout:
                canvas:
                    Color:
                        rgba: (.37/2.5, .39/2.5, .45/2.5, 1)
                    Rectangle:
                        pos: self.pos
                        size: 1000,417
                CustButton:
                    id:b1006
                    pos: 277,20
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.trackselected(b1006)
                    on_press: pmode.midiportselect()
                CustButton:
                    id:b1005
                    pos: 277,80
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.trackselected(b1005)
                    on_press: pmode.midiportselect()
                CustButton:
                    id:b1004
                    pos: 277,140
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.trackselected(b1004)
                    on_press: pmode.midiportselect()
                CustButton:
                    id:b1003
                    pos: 277,200
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.trackselected(b1003)
                    on_press: pmode.midiportselect()
                CustButton:
                    id:b1002
                    pos: 277,260
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.trackselected(b1002)
                    on_press: pmode.midiportselect()
                CustButton:
                    id:b1001
                    pos: 277,320
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.trackselected(b1001)
                    on_press: pmode.midiportselect()
                CustButton:
                    id:b2006
                    pos: 428,20
                    size: 150, 55
                    text: "6"
                    background_color: .68,.68,.84,1
                    on_press:pmode.trackselected(b2006)
                    on_press: pmode.midichannelselect()
                CustButton:
                    id:b2005
                    pos: 428,80
                    size: 150, 55
                    text: "5"
                    background_color: .68,.68,.84,1
                    on_press:pmode.trackselected(b2005)
                    on_press: pmode.midichannelselect()
                CustButton:
                    id:b2004
                    pos: 428,140
                    size: 150, 55
                    text: "4"
                    background_color: .68,.68,.84,1
                    on_press:pmode.trackselected(b2004)
                    on_press: pmode.midichannelselect()
                CustButton:
                    id:b2003
                    pos: 428,200
                    size: 150, 55
                    text: "3"
                    background_color: .68,.68,.84,1
                    on_press:pmode.trackselected(b2003)
                    on_press: pmode.midichannelselect()
                CustButton:
                    id:b2002
                    pos: 428,260
                    size: 150, 55
                    text: "2"
                    background_color: .68,.68,.84,1
                    on_press:pmode.trackselected(b2002)
                    on_press: pmode.midichannelselect()
                CustButton:
                    id:b2001
                    pos: 428,320
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.trackselected(b2001)
                    on_press: pmode.midichannelselect()
                CustButton2:
                    id:b2007
                    pos: 1723,80
                    size: 65, 55
                    text: "Up"
                    background_color: .68,.68,.84,1
                    on_press: pmode.scrollUpMIDI()
                CustButton2:
                    id:b2008
                    pos: 1723,20
                    size: 65, 55
                    text: "Down"
                    background_color: .68,.68,.84,1
                    on_press: pmode.scrollDownMIDI()
                Label:
                    id: lbl6
                    text:'Track6:'
                    font_size: 22
                    pos: 160,0
                Label:
                    id: lbl5
                    text:'Track5:'
                    font_size: 22
                    pos: 160,60
                Label:
                    id: lbl4    
                    text:'Track4:'
                    font_size: 22
                    pos: 160,120
                Label:
                    id: lbl3
                    text:'Track3:'
                    font_size: 22
                    pos: 160,180
                Label:
                    id: lbl2
                    text:'Track2:'
                    font_size: 22
                    pos: 160,240
                Label:
                    id: lbl1
                    text:'Track1:'
                    font_size: 22
                    pos: 160,300
                Label:
                    text:'Port:'
                    font_size: 22
                    pos: 305,340
                Label:
                    text:'Channel:'
                    font_size: 22
                    pos: 450,340

        TabbedPanelItem:
            on_press:pmode.closemenu()          
            text:'CV'
            background_color :.68,.68,.84,1
            font_size: 25
            font_name:"Calibri"
            size: 150, 60

            GridLayout:
                canvas:
                    Color:
                        rgba: (.37/2.5, .39/2.5, .45/2.5, 1)
                    Rectangle:
                        pos: self.pos
                        size: 1000,417
                CustButton:
                    id:b10006
                    pos: 177,20
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b10006)
                    on_press: pmode.CVTypeselect()
                CustButton:
                    id:b10005
                    pos: 177,80
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b10005)
                    on_press: pmode.CVTypeselect()
                CustButton:
                    id:b10004
                    pos: 177,140
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b10004)
                    on_press: pmode.CVTypeselect()
                CustButton:
                    id:b10003
                    pos: 177,200
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b10003)
                    on_press: pmode.CVTypeselect()
                CustButton:
                    id:b10002
                    pos: 177,260
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b10002)
                    on_press: pmode.CVTypeselect()
                CustButton:
                    id:b10001
                    pos: 177,320
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b10001)
                    on_press: pmode.CVTypeselect()
                CustButton:
                    id:b20006
                    pos: 328,20
                    size: 150, 55
                    text: "6"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b20006)
                    on_press: pmode.CVTrackselect()
                CustButton:
                    id:b20005
                    pos: 328,80
                    size: 150, 55
                    text: "5"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b20005)
                    on_press: pmode.CVTrackselect()
                CustButton:
                    id:b20004
                    pos: 328,140
                    size: 150, 55
                    text: "4"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b20004)
                    on_press: pmode.CVTrackselect()
                CustButton:
                    id:b20003
                    pos: 328,200
                    size: 150, 55
                    text: "3"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b20003)
                    on_press: pmode.CVTrackselect()
                CustButton:
                    id:b20002
                    pos: 328,260
                    size: 150, 55
                    text: "2"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b20002)
                    on_press: pmode.CVTrackselect()
                CustButton:
                    id:b20001
                    pos: 328,320
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b20001)
                    on_press: pmode.CVTrackselect()
                CustButton:
                    id:b30006
                    pos: 479,20
                    size: 150, 55
                    text: "6"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b20006)
                    on_press: pmode.CVVoltageselect()
                CustButton:
                    id:b30005
                    pos: 479,80
                    size: 150, 55
                    text: "5"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b20005)
                    on_press: pmode.CVVoltageselect()
                CustButton:
                    id:b30004
                    pos: 479,140
                    size: 150, 55
                    text: "4"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b20004)
                    on_press: pmode.CVVoltageselect()
                CustButton:
                    id:b30003
                    pos: 479,200
                    size: 150, 55
                    text: "3"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b20003)
                    on_press: pmode.CVVoltageselect()
                CustButton:
                    id:b30002
                    pos: 479,260
                    size: 150, 55
                    text: "2"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b20002)
                    on_press: pmode.CVVoltageselect()
                CustButton:
                    id:b30001
                    pos: 479,320
                    size: 150, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press:pmode.CVselected(b20001)
                    on_press: pmode.CVVoltageselect()
                CustButton2:
                    id:b20007
                    pos: 1723,80
                    size: 65, 55
                    text: "Up"
                    background_color: .68,.68,.84,1
                    on_press: pmode.scrollUpCV()
                CustButton2:
                    id:b20008
                    pos: 1723,20
                    size: 65, 55
                    text: "Down"
                    background_color: .68,.68,.84,1
                    on_press: pmode.scrollDownCV()
                Label:
                    id: lbl60
                    text:'CV6:'
                    font_size: 22
                    pos: 60,0
                Label:
                    id: lbl50
                    text:'CV5:'
                    font_size: 22
                    pos: 60,60
                Label:
                    id: lbl40   
                    text:'CV4:'
                    font_size: 22
                    pos: 60,120
                Label:
                    id: lbl30
                    text:'CV3:'
                    font_size: 22
                    pos: 60,180
                Label:
                    id: lbl20
                    text:'CV2:'
                    font_size: 22
                    pos: 60,240
                Label:
                    id: lbl10
                    text:'CV1:'
                    font_size: 22
                    pos: 60,300
                Label:
                    text:'Type:'
                    font_size: 22
                    pos: 200,340
                Label:
                    text:'Track:'
                    font_size: 22
                    pos: 350,340
                Label:
                    text:'Voltage:'
                    font_size: 22
                    pos: 500,340








        TabbedPanelItem:
            on_press:pmode.closemenu()
            on_press:pmode.syncupdate()
            text:'SYNC'
            background_color :.68,.68,.84,1
            font_size: 25
            font_name:"Calibri"
            size: 150, 60

            GridLayout:
                canvas:
                    Color:
                        rgba: (.37/2.5, .39/2.5, .45/2.5, 1)
                    Rectangle:
                        pos: self.pos
                        size: 1000,417
                CustButton:
                    id:b100001
                    pos: 230,290
                    size: 55, 55
                    background_color: .68,.68,.84,1
                    on_press: pmode.MIDIsync()
                    on_press: b100001.state='normal'
                CustButton:
                    id:b100002
                    pos: 230,190
                    size: 55, 55
                    background_color: .68,.68,.84,1
                    on_press: pmode.USBsync()
                    on_press: b100002.state='normal'                    
                CustButton:
                    id:b100003
                    pos: 210,90
                    size: 100, 55
                    text: "1"
                    background_color: .68,.68,.84,1
                    on_press: pmode.PPQselect()
                Label:
                    text:'DIN Out SYNC:'
                    font_size: 22
                    pos: 70,270
                Label:
                    text:'USB Out SYNC:'
                    font_size: 22
                    pos: 70,170
                Label:
                    text:'Clock PPQ:       '
                    font_size: 22
                    pos: 70,70                        
                Label:
                    text:'USB Out PPQ:'
                    font_size: 22
                    pos: 340,170
                Label:
                    text:'MIDI USB:'
                    font_size: 22
                    pos: 340,270    
                Label:
                    text:'DIN In:'
                    font_size: 22
                    pos: 560,270 
                CustButton:
                    id:b100006
                    pos: 670,290
                    size: 55, 55
                    text:'Off'
                    background_color: .68,.68,.84,1
                    on_press:pmode.DINin()
                    on_press:b100006.state='normal'
                CustButton:
                    id:b100004
                    pos: 470,190
                    size: 55, 55
                    background_color: .68,.68,.84,1
                    on_press:pmode.BPMmult()
                    on_press: b100004.state='normal' 
                CustButton:
                    id:b100005
                    pos: 470,290
                    size: 55, 55
                    background_color: .68,.68,.84,1
                    on_press:pmode.USBstate()
                    on_press: b100005.state='normal'                      

        TabbedPanelItem:
            on_press:pmode.closemenu()
            text:'OTHER'
            background_color :.68,.68,.84,1
            font_size: 25
            font_name:"Calibri"
            size: 150, 60

            GridLayout:
                canvas:
                    Color:
                        rgba: (.37/2.5, .39/2.5, .45/2.5, 1)
                    Rectangle:
                        pos: self.pos
                        size: 1000,417
                CustButton:
                    id:b1000001
                    pos: 260,290
                    size: 55, 55
                    text:'20'
                    background_color: .68,.68,.84,1
                    on_press: pmode.brightness(20)
                    on_press: b1000002.state='normal'
                    on_press: b1000003.state='normal'
                    on_press: b1000001.state='down'
                CustButton:
                    id:b1000002
                    pos: 330,290
                    size: 55, 55
                    text:'50'
                    background_color: .68,.68,.84,1
                    on_press: pmode.brightness(50)
                    on_press: b1000001.state='normal'
                    on_press: b1000003.state='normal'
                    on_press: b1000002.state='down'
                CustButton:
                    id:b1000003
                    pos: 400,290
                    size: 55, 55
                    text:'100'
                    background_color: .68,.68,.84,1
                    on_press: pmode.brightness(100)
                    on_press: b1000002.state='normal'
                    on_press: b1000001.state='normal'  
                    on_press: b1000003.state='down'                                    
                CustButton2:
                    pos: 60,190
                    size: 180, 55
                    font_size: 25
                    text:'Update'
                    background_color: .68,.68,.84,1
                    on_press: pmode.update()
                    on_press: b100002.state='normal'                    
                CustButton2:
                    pos: 60,90
                    font_size: 25
                    size: 180, 55
                    text: "Shutdown"
                    background_color: .68,.68,.84,1
                    on_press: pmode.kill()
                Label:
                    text:'Brightness:'
                    font_size: 22
                    pos: 100,270
                Label:
                    id:b1000004
                    text: "Version"
                    font_size: 20
                    pos: 350,0
                Label:
                    id:b1000005
                    text: "Updating.."
                    font_size: 20
                    pos: 310,1190                
                CustButton2:
                    pos: 780,-20
                    font_size: 25
                    size: 180, 55
                    text: "Dev Mode"
                    background_color: (.37, .39, .45, 0.4)
                    on_press: pmode.close()


    GridLayout:
        CustButton3:
            pos: 648,419
            size: 150, 60
            text: "CLOSE"
            id:b007
            on_press:root.manager.current='song_mode'
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.closemenu()
            on_press: pmode.leaving()

        CustButton3:
            id:b3005
            pos: 1000,0
            size: 1000,419
            background_color: 1,1,1,0.5
            on_press:pmode.closemenu()
            



        Widget:
            id:b4000
            pos:1300,1120
            canvas:
                Color:
                    rgba: (.37/2.5, .39/2.5, .45/2.5, 1)
                Rectangle:
                    pos: (self.pos[0]-3,self.pos[1]-3)
                    size: 206,190
                Color:
                    rgba: (.37/1.7, .39/1.7, .45/1.7, 1)
                Rectangle:
                    pos: self.pos
                    size: 200,184 


        CustButton3:
            pos: 1301,1121
            size: 198,60
            text: "2"
            id:b4001
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port1(b4002)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 198,60
            text: "1"
            id:b4002
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port1(b4001)
            on_press:pmode.closemenu()

        Label:
            pos: 1301,1243
            size: 198,60
            text: "MIDI PORT:"
            id:b4003
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1



        Widget:
            id:b5000
            pos:1300,1120
            canvas:
                Color:
                    rgba: (.37/2.5, .39/2.5, .45/2.5, 1)
                Rectangle:
                    pos: (self.pos[0]-3,self.pos[1]-3)
                    size: 528,340
                Color:
                    rgba: (.37/1.7, .39/1.7, .45/1.7, 1)
                Rectangle:
                    pos: self.pos
                    size: 522,334 


        CustButton3:
            pos: 1301,1121
            size: 130,67
            text: "01"
            id:b5001
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5001)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 130,67
            text: "02"
            id:b5002
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5002)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 130,67
            text: "03"
            id:b5003
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5003)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 130,67
            text: "04"
            id:b5004
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5004)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1121
            size: 130,67
            text: "05"
            id:b5005
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5005)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 130,67
            text: "06"
            id:b5006
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5006)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 130,67
            text: "07"
            id:b5007
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5007)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 130,67
            text: "08"
            id:b5008
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5008)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1121
            size: 130,67
            text: "09"
            id:b5009
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5009)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 130,67
            text: "10"
            id:b5010
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5010)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 130,67
            text: "11"
            id:b5011
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5011)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 130,67
            text: "12"
            id:b5012
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5012)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1121
            size: 130,67
            text: "13"
            id:b5013
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5013)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 130,67
            text: "14"
            id:b5014
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5014)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 130,67
            text: "15"
            id:b5015
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5015)
            on_press:pmode.closemenu()
        CustButton3:
            pos: 1301,1182
            size: 130,67
            text: "16"
            id:b5016
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:pmode.port2(b5016)
            on_press:pmode.closemenu()



        Label:
            pos: 1301,1243
            size: 198,60
            text: "MIDI CHANNEL:"
            id:b5017
            font_size: 28
            font_name:"Calibri"
            background_color: .68,.68,.84,1







































<SongScreen>
    id:smode
    b001:b001
    b002:b002
    b003:b003
    b004:b004
    b005:b005
    b006:b006
    b007:b007
    b008:b008
    b009:b009
    b010:b010
    b011:b011
    b012:b012
    b013:b013
    b014:b014
    b015:b015
    b017:b017
    b019:b019
    b020:b020
    b021:b021
    b022:b022

    b101: b101
    b100: b100
    b200: b200
    b300: b300
    b400: b400
    b500: b500
    b600: b600
    b700: b700
    b800: b800

    b901: b901
    b902: b902
    b903: b903
    b904: b904
    b905: b905
    b906: b906
    b907: b907
    b908: b908
    b909: b909
    b910: b910
    b911: b911
    b912: b912
    b913: b913
    b914: b914
    b915: b915
    b916: b916
    



    GridLayout:
        canvas.before:
            Color:
                rgba: (.37, .39, .45, 0.4)
            Rectangle:
                pos: self.pos
                size: self.size








        CustButton4:
            pos: 1,1
            text: "8"
            font_size: 18
            id:b100
            background_color: (.37, .39, .45, 0.4)
            on_press:smode.trackmenu(b100)            
        CustButton4:
            pos: 1,48
            text: "7"
            font_size: 18
            id:b200
            background_color: (.37, .39, .45, 0.4)
            on_press:smode.trackmenu(b200)            
        CustButton4:
            pos: 1,95
            text: "6"
            font_size: 18
            id:b300
            background_color: (.37, .39, .45, 0.4)
            on_press:smode.trackmenu(b300)
        CustButton4:
            pos: 1,142
            text: "5"
            font_size: 18
            id:b400
            background_color: (.37, .39, .45, 0.4)
            on_press:smode.trackmenu(b400)            
        CustButton4:
            pos: 1,189
            text: "4"
            font_size: 18
            id:b500
            background_color: (.37, .39, .45, 0.4)
            on_press:smode.trackmenu(b500)            
        CustButton4:
            pos: 1,236
            text: "3"
            font_size: 18
            id:b600
            background_color: (.37, .39, .45, 0.4)
            on_press:smode.trackmenu(b600)            
            
        CustButton4:
            pos: 1,283
            text: "2"
            font_size: 18
            id:b700
            background_color: (.37, .39, .45, 0.4)
            on_press:smode.trackmenu(b700)            
            
        CustButton4:
            pos: 1,330
            text: "1"
            font_size: 18
            id:b800
            background_color: (.37, .39, .45, 0.4)
            on_press:smode.trackmenu(b800)
            
            


        CustButton3:
            pos: 49,377
            background_color: (.37, .39, .45, 0)
            id:b901
            text: "1"
        CustButton3:
            pos: 96,377
            background_color: (.37, .39, .45, 0)
            id:b902
            text: "5"
        CustButton3:
            pos: 143,377
            background_color: (.37, .39, .45, 0)
            id:b903
            text: "9"
        CustButton3:
            pos: 190,377
            background_color: (.37, .39, .45, 0)
            id:b904
            text: "13"
        CustButton3:
            pos: 237,377
            background_color: (.37, .39, .45, 0)
            id:b905
            text: "17"
        CustButton3:
            pos: 284,377
            background_color: (.37, .39, .45, 0)
            id:b906
            text: "21"
        CustButton3:
            pos: 331,377
            background_color: (.37, .39, .45, 0)
            id:b907
            text: "25"
        CustButton3:
            pos: 378,377
            background_color: (.37, .39, .45, 0)
            id:b908
            text: "29"
        CustButton3:
            pos: 425,377
            background_color: (.37, .39, .45, 0)
            id:b909
            text: "33"
        CustButton3:
            pos: 472,377
            background_color: (.37, .39, .45, 0)
            id:b910
            text: "37"
        CustButton3:
            pos: 519,377
            background_color: (.37, .39, .45, 0)
            id:b911
            text: "41"
        CustButton3:
            pos: 566,377
            background_color: (.37, .39, .45, 0)
            id:b912
            text: "45"
        CustButton3:
            pos: 613,377
            background_color: (.37, .39, .45, 0)
            id:b913
            text: "49"
        CustButton3:
            pos: 660,377
            background_color: (.37, .39, .45, 0)
            id:b914
            text: "53"
        CustButton3:
            pos: 707,377
            background_color: (.37, .39, .45, 0)
            id:b915
            text: "57"
        CustButton3:
            pos: 754,377
            background_color: (.37, .39, .45, 0)
            id:b916
            text: "61"




        CustButton:
            pos: 49,1
            id:b101
            on_press: smode.monitor(b101)
        CustButton:
            pos: 96,1
            id:b102
            on_press: smode.monitor(b102)
        CustButton:
            pos: 143,1
            id:b103
            on_press: smode.monitor(b103)
        CustButton:
            pos: 190,1
            id:b104
            on_press: smode.monitor(b104)
        CustButton:
            pos: 237,1
            id:b105
            on_press: smode.monitor(b105)
        CustButton:
            pos: 284,1
            id:b106
            on_press: smode.monitor(b106)
        CustButton:
            pos: 331,1
            id:b107
            on_press: smode.monitor(b107)
        CustButton:
            pos: 378,1
            id:b108
            on_press: smode.monitor(b108)
        CustButton:
            pos: 425,1
            id:b109
            on_press: smode.monitor(b109)
        CustButton:
            pos: 472,1
            id:b110
            on_press: smode.monitor(b110)
        CustButton:
            pos: 519,1
            id:b111
            on_press: smode.monitor(b111)
        CustButton:
            pos: 566,1
            id:b112
            on_press: smode.monitor(b112)
        CustButton:
            pos: 613,1
            id:b113
            on_press: smode.monitor(b113)
        CustButton:
            pos: 660,1 
            id:b114
            on_press: smode.monitor(b114)
        CustButton:
            pos: 707,1
            id:b115
            on_press: smode.monitor(b115)
        CustButton:
            pos: 754,1
            id:b116
            on_press: smode.monitor(b116)


        CustButton:
            pos: 49,48
            id:b201
            on_press: smode.monitor(b201)
        CustButton:
            pos: 96,48
            id:b202
            on_press: smode.monitor(b202)
        CustButton:
            pos: 143,48
            id:b203
            on_press: smode.monitor(b203)
        CustButton:
            pos: 190,48
            id:b204
            on_press: smode.monitor(b204)
        CustButton:
            pos: 237,48
            id:b205
            on_press: smode.monitor(b205)
        CustButton:
            pos: 284,48
            id:b206
            on_press: smode.monitor(b206)
        CustButton:
            pos: 331,48
            id:b207
            on_press: smode.monitor(b207)
        CustButton:
            pos: 378,48
            id:b208
            on_press: smode.monitor(b208)
        CustButton:
            pos: 425,48
            id:b209
            on_press: smode.monitor(b209)
        CustButton:
            pos: 472,48
            id:b210
            on_press: smode.monitor(b210)
        CustButton:
            pos: 519,48
            id:b211
            on_press: smode.monitor(b211)
        CustButton:
            pos: 566,48
            id:b212
            on_press: smode.monitor(b212)
        CustButton:
            pos: 613,48
            id:b213
            on_press: smode.monitor(b213)
        CustButton:
            pos: 660,48
            id:b214
            on_press: smode.monitor(b214)
        CustButton:
            pos: 707,48
            id:b215
            on_press: smode.monitor(b215)
        CustButton:
            pos: 754,48
            id:b216
            on_press: smode.monitor(b216)

        

        CustButton:
            pos: 49,95
            id:b301
            on_press: smode.monitor(b301)
        CustButton:
            pos: 96,95
            id:b302
            on_press: smode.monitor(b302)
        CustButton:
            pos: 143,95
            id:b303
            on_press: smode.monitor(b303)
        CustButton:
            pos: 190,95       
            id:b304
            on_press: smode.monitor(b304)
        CustButton:
            pos: 237,95
            id:b305
            on_press: smode.monitor(b305)
        CustButton:
            pos: 284,95
            id:b306
            on_press: smode.monitor(b306)
        CustButton:
            pos: 331,95
            id:b307
            on_press: smode.monitor(b307)
        CustButton:
            pos: 378,95
            id:b308
            on_press: smode.monitor(b308)
        CustButton:
            pos: 425,95
            id:b309
            on_press: smode.monitor(b309)
        CustButton:
            pos: 472,95
            id:b310
            on_press: smode.monitor(b310)
        CustButton:
            pos: 519,95
            id:b311
            on_press: smode.monitor(b311)
        CustButton:
            pos: 566,95
            id:b312
            on_press: smode.monitor(b312)
        CustButton:
            pos: 613,95
            id:b313
            on_press: smode.monitor(b313)
        CustButton:
            pos: 660,95
            id:b314
            on_press: smode.monitor(b314)
        CustButton:
            pos: 707,95
            id:b315
            on_press: smode.monitor(b315)
        CustButton:
            pos: 754,95
            id:b316
            on_press: smode.monitor(b316)


        CustButton:
            pos: 49,142
            id:b401
            on_press: smode.monitor(b401)
        CustButton:
            pos: 96,142
            id:b402
            on_press: smode.monitor(b402)
        CustButton:
            pos: 143,142
            id:b403
            on_press: smode.monitor(b403)
        CustButton:
            pos: 190,142
            id:b404
            on_press: smode.monitor(b404)
        CustButton:
            pos: 237,142
            id:b405
            on_press: smode.monitor(b405)
        CustButton:
            pos: 284,142
            id:b406
            on_press: smode.monitor(b406)
        CustButton:
            pos: 331,142
            id:b407
            on_press: smode.monitor(b407)
        CustButton:
            pos: 378,142
            id:b408
            on_press: smode.monitor(b408)
        CustButton:
            pos: 425,142
            id:b409
            on_press: smode.monitor(b409)
        CustButton:
            pos: 472,142
            id:b410
            on_press: smode.monitor(b410)
        CustButton:
            pos: 519,142
            id:b411
            on_press: smode.monitor(b411)
        CustButton:
            pos: 566,142
            id:b412
            on_press: smode.monitor(b412)
        CustButton:
            pos: 613,142
            id:b413
            on_press: smode.monitor(b413)
        CustButton:
            pos: 660,142
            id:b414
            on_press: smode.monitor(b414)
        CustButton:
            pos: 707,142
            id:b415
            on_press: smode.monitor(b415)
        CustButton:
            pos: 754,142
            id:b416
            on_press: smode.monitor(b416)



        CustButton:
            pos: 49,189
            id:b501
            on_press: smode.monitor(b501)
        CustButton:
            pos: 96,189
            id:b502
            on_press: smode.monitor(b502)
        CustButton:
            pos: 143,189
            id:b503
            on_press: smode.monitor(b503)
        CustButton:
            pos: 190,189
            id:b504
            on_press: smode.monitor(b504)
        CustButton:
            pos: 237,189
            id:b505
            on_press: smode.monitor(b505)
        CustButton:
            pos: 284,189
            id:b506
            on_press: smode.monitor(b506)
        CustButton:
            pos: 331,189
            id:b507
            on_press: smode.monitor(b507)
        CustButton:
            pos: 378,189
            id:b508
            on_press: smode.monitor(b508)
        CustButton:
            pos: 425,189
            id:b509
            on_press: smode.monitor(b509)
        CustButton:
            pos: 472,189
            id:b510
            on_press: smode.monitor(b510)
        CustButton:
            pos: 519,189
            id:b511
            on_press: smode.monitor(b511)
        CustButton:
            pos: 566,189
            id:b512
            on_press: smode.monitor(b512)
        CustButton:
            pos: 613,189
            id:b513
            on_press: smode.monitor(b513)
        CustButton:
            pos: 660,189
            id:b514
            on_press: smode.monitor(b514)
        CustButton:
            pos: 707,189
            id:b515
            on_press: smode.monitor(b515)
        CustButton:
            pos: 754,189
            id:b516
            on_press: smode.monitor(b516)





        CustButton:
            pos: 49,236
            id:b601
            on_press: smode.monitor(b601)
        CustButton:
            pos: 96,236
            id:b602
            on_press: smode.monitor(b602)
        CustButton:
            pos: 143,236
            id:b603
            on_press: smode.monitor(b603)
        CustButton:
            pos: 190,236
            id:b604
            on_press: smode.monitor(b604)
        CustButton:
            pos: 237,236
            id:b605
            on_press: smode.monitor(b605)
        CustButton:
            pos: 284,236
            id:b606
            on_press: smode.monitor(b606)
        CustButton:
            pos: 331,236
            id:b607
            on_press: smode.monitor(b607)
        CustButton:
            pos: 378,236
            id:b608
            on_press: smode.monitor(b608)
        CustButton:
            pos: 425,236
            id:b609
            on_press: smode.monitor(b609)
        CustButton:
            pos: 472,236
            id:b610
            on_press: smode.monitor(b610)
        CustButton:
            pos: 519,236
            id:b611
            on_press: smode.monitor(b611)
        CustButton:
            pos: 566,236
            id:b612
            on_press: smode.monitor(b612)
        CustButton:
            pos: 613,236
            id:b613
            on_press: smode.monitor(b613)
        CustButton:
            pos: 660,236
            id:b614
            on_press: smode.monitor(b614)
        CustButton:
            pos: 707,236
            id:b615
            on_press: smode.monitor(b615)
        CustButton:
            pos: 754,236
            id:b616
            on_press: smode.monitor(b616)


        CustButton:
            pos: 49,283
            id:b701
            on_press: smode.monitor(b701)
        CustButton:
            pos: 96,283
            id:b702
            on_press: smode.monitor(b702)
        CustButton:
            pos: 143,283
            id:b703
            on_press: smode.monitor(b703)
        CustButton:
            pos: 190,283
            id:b704
            on_press: smode.monitor(b704)
        CustButton:
            pos: 237,283
            id:b705
            on_press: smode.monitor(b705)
        CustButton:
            pos: 284,283
            id:b706
            on_press: smode.monitor(b706)
        CustButton:
            pos: 331,283
            id:b707
            on_press: smode.monitor(b707)
        CustButton:
            pos: 378,283
            id:b708
            on_press: smode.monitor(b708)
        CustButton:
            pos: 425,283
            id:b709
            on_press: smode.monitor(b709)
        CustButton:
            pos: 472,283
            id:b710
            on_press: smode.monitor(b710)
        CustButton:
            pos: 519,283
            id:b711
            on_press: smode.monitor(b711)
        CustButton:
            pos: 566,283
            id:b712
            on_press: smode.monitor(b712)
        CustButton:
            pos: 613,283
            id:b713
            on_press: smode.monitor(b713)
        CustButton:
            pos: 660,283
            id:b714
            on_press: smode.monitor(b714)
        CustButton:
            pos: 707,283
            id:b715
            on_press: smode.monitor(b715)
        CustButton:
            pos: 754,283
            id:b716
            on_press: smode.monitor(b716)

        CustButton:
            pos: 49,330
            id:b801
            state:'down'
            on_press: smode.monitor(b801)
        CustButton:
            pos: 96,330
            id:b802
            state:'down'
            on_press: smode.monitor(b802)
        CustButton:
            pos: 143,330
            id:b803
            state:'down'
            on_press: smode.monitor(b803)
        CustButton:
            pos: 190,330
            id:b804
            state:'down'
            on_press: smode.monitor(b804)
        CustButton:
            pos: 237,330
            id:b805
            state:'down'
            on_press: smode.monitor(b805)
        CustButton:
            pos: 284,330
            id:b806
            state:'down'
            on_press: smode.monitor(b806)
        CustButton:
            pos: 331,330
            id:b807
            state:'down'
            on_press: smode.monitor(b807)
        CustButton:
            pos: 378,330
            id:b808
            state:'down'
            on_press: smode.monitor(b808)
        CustButton:
            pos: 425,330
            id:b809
            state:'down'
            on_press: smode.monitor(b809)
        CustButton:
            pos: 472,330
            id:b810
            state:'down'
            on_press: smode.monitor(b810)
        CustButton:
            pos: 519,330
            id:b811
            state:'down'
            on_press: smode.monitor(b811)
        CustButton:
            pos: 566,330
            id:b812
            state:'down'
            on_press: smode.monitor(b812)
        CustButton:
            pos: 613,330
            id:b813
            state:'down'
            on_press: smode.monitor(b813)
        CustButton:
            pos: 660,330
            id:b814
            state:'down'
            on_press: smode.monitor(b814)
        CustButton:
            pos: 707,330
            id:b815
            state:'down'
            on_press: smode.monitor(b815)
        CustButton:
            pos: 754,330
            id:b816
            state:'down'
            on_press: smode.monitor(b816)






        CustButton3:
            id:b017
            pos: 1000,1000
            size: 15,415
            background_color: (0.5, 0, 0, 1)
            on_press: b017.state='normal'
        CustButton3:
            id:b015
            pos: 1000,1000
            size: 15,415
            background_color: (.37, .39, .45, 1)  
            on_press: b015.state='normal'


















        CustToggleButton:
            markup: True
            pos: 1,419
            size: 90, 60
            text: "%s"%(icon('icon-play', 22))
            id:b001
            on_press: smode.start()
        CustButton3:
            markup: True
            pos: 93,419
            size: 90, 60
            text: "%s"%(icon('icon-stop', 22))
            id:b002
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: smode.stop()
        CustToggleButton:
            pos: 185,419
            size: 60, 60
            id:b003
            on_press:smode.mode(2)   
            on_press:b004.state='normal'
            on_press:smode.closemenus()

            font_size: 27
            text: "120"
        CustToggleButton:
            pos: 247,419
            size: 95, 60
            text: "16"
            on_press:smode.mode(3)
            on_press:b003.state='normal'
            on_press:smode.closemenus()
            font_size: 27
            id:b004
        CustToggleButton:
            pos: 344,419
            size: 150, 60
            text: "TOOLS"
            id:b005
            on_press: b005.state='normal'
        CustToggleButton:
            pos: 496,419
            size: 150, 60
            text: "SONG"
            id:b006
            on_press: b006.state='normal'
        CustToggleButton:
            pos: 648,419
            size: 150, 60
            text: "MENU"
            id:b007
            on_press: smode.menu()

        CustButton3:
            id:b010
            pos: 1000,0
            size: 1000,419
            background_color: 0,0,0,0
            on_press: smode.closemenus()


        CustButton3:
            pos: 648,900
            size: 150,60
            text: "SEQ"
            id:b008
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.transition.direction='right'
            on_press:root.manager.current='piano_roll'
            on_press: smode.closemenus()
            on_press: smode.leaving()

        CustButton3:
            pos: 648,900
            size: 150,60
            text: "PARAM"
            id:b009
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.current='param_mode'
            on_press: smode.closemenus()
            on_press: smode.leaving()


        CustButton3:
            markup: True
            pos: 344,900
            size: 150,60
            text: "EFFECTS %s"%(icon('icon-lock', 22))
            id:b011
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: smode.closemenus()

        CustButton3:
            markup: True
            pos: 344,900
            size: 150,60
            text: "MIXER %s"%(icon('icon-lock', 22))
            id:b012
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: smode.closemenus()

        CustButton3:
            pos: 496,900
            size: 150,60
            text: "SAVE"
            id:b013
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1

        CustButton3:
            pos: 496,900
            size: 150,60
            text: "LOAD"
            id:b014
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1




        Widget:
            id:b019
            pos:1300,1120
            canvas:
                Color:
                    rgba: (.37/2.5, .39/2.5, .45/2.5, 1)
                Rectangle:
                    pos: (self.pos[0]-3,self.pos[1]-3)
                    size: 206,190
                Color:
                    rgba: (.37/1.7, .39/1.7, .45/1.7, 1)
                Rectangle:
                    pos: self.pos
                    size: 200,184 


        CustButton3:
            pos: 1301,1121
            size: 198,60
            text: "CLEAR"
            id:b020
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: smode.cleartrack()
            on_press: smode.closemenus()
        CustButton3:
            pos: 1301,1182
            size: 198,60
            text: "ASSIGN"
            id:b021
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.current='param_mode'
            on_press: smode.closemenus()
            on_press: smode.leaving()            
        CustButton3:
            pos: 1301,1243
            size: 198,60
            text: "EDIT"
            id:b022
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.transition.direction='right'
            on_press:root.manager.current='piano_roll'
            on_press: smode.closemenus()
            on_press: smode.leaving()













































 

<SeqScreen>:
    id: sequencer
    b101: b101
    b100: b100
    b200: b200
    b300: b300
    b400: b400
    b500: b500
    b600: b600
    b700: b700
    b800: b800

    b901: b901
    b902: b902
    b903: b903
    b904: b904
    b905: b905
    b906: b906
    b907: b907
    b908: b908
    b909: b909
    b910: b910
    b911: b911
    b912: b912
    b913: b913
    b914: b914
    b915: b915
    b916: b916



    b001:b001
    b002:b002
    b003:b003
    b004:b004
    b005:b005
    b006:b006
    b007:b007
    b008:b008
    b009:b009
    b010:b010
    b011:b011
    b012:b012
    b013:b013
    b014:b014
    b015:b015
    b016:b016
    b017:b017
    b018:b018
    b019:b019
    b020:b020
    b021:b021
    b022:b022

    
    

    GridLayout:
        
    
        canvas.before:
           

            Color:
                rgba: (.37, .39, .45, 0.4)
            Rectangle:
                pos: self.pos
                size: self.size
            
            
        
        Widget:
            id:b018
            pos:235,0
            canvas:
                Color:
                    rgba: (1, 1, 1, 0.4)
                Rectangle:
                    pos: self.pos
                    size: 2,385 
                Rectangle:
                    pos: (self.pos[0]+188, self.pos[1])
                    size: 2,385 
                Rectangle:
                    pos: (self.pos[0]+376, self.pos[1])
                    size: 2,385 
                Rectangle:
                    pos: (self.pos[0]+564, self.pos[1])
                    size: 2,385 
        
        

        





        CustButton:
            pos: 49,1
            id:b101
            on_press: sequencer.monitor(b101)
        CustButton:
            pos: 96,1
            id:b102
            on_press: sequencer.monitor(b102)
        CustButton:
            pos: 143,1
            id:b103
            on_press: sequencer.monitor(b103)
        CustButton:
            pos: 190,1
            id:b104
            on_press: sequencer.monitor(b104)
        CustButton:
            pos: 237,1
            id:b105
            on_press: sequencer.monitor(b105)
        CustButton:
            pos: 284,1
            id:b106
            on_press: sequencer.monitor(b106)
        CustButton:
            pos: 331,1
            id:b107
            on_press: sequencer.monitor(b107)
        CustButton:
            pos: 378,1
            id:b108
            on_press: sequencer.monitor(b108)
        CustButton:
            pos: 425,1
            id:b109
            on_press: sequencer.monitor(b109)
        CustButton:
            pos: 472,1
            id:b110
            on_press: sequencer.monitor(b110)
        CustButton:
            pos: 519,1
            id:b111
            on_press: sequencer.monitor(b111)
        CustButton:
            pos: 566,1
            id:b112
            on_press: sequencer.monitor(b112)
        CustButton:
            pos: 613,1
            id:b113
            on_press: sequencer.monitor(b113)
        CustButton:
            pos: 660,1 
            id:b114
            on_press: sequencer.monitor(b114)
        CustButton:
            pos: 707,1
            id:b115
            on_press: sequencer.monitor(b115)
        CustButton:
            pos: 754,1
            id:b116
            on_press: sequencer.monitor(b116)


        CustButton:
            pos: 49,48
            id:b201
            on_press: sequencer.monitor(b201)
        CustButton:
            pos: 96,48
            id:b202
            on_press: sequencer.monitor(b202)
        CustButton:
            pos: 143,48
            id:b203
            on_press: sequencer.monitor(b203)
        CustButton:
            pos: 190,48
            id:b204
            on_press: sequencer.monitor(b204)
        CustButton:
            pos: 237,48
            id:b205
            on_press: sequencer.monitor(b205)
        CustButton:
            pos: 284,48
            id:b206
            on_press: sequencer.monitor(b206)
        CustButton:
            pos: 331,48
            id:b207
            on_press: sequencer.monitor(b207)
        CustButton:
            pos: 378,48
            id:b208
            on_press: sequencer.monitor(b208)
        CustButton:
            pos: 425,48
            id:b209
            on_press: sequencer.monitor(b209)
        CustButton:
            pos: 472,48
            id:b210
            on_press: sequencer.monitor(b210)
        CustButton:
            pos: 519,48
            id:b211
            on_press: sequencer.monitor(b211)
        CustButton:
            pos: 566,48
            id:b212
            on_press: sequencer.monitor(b212)
        CustButton:
            pos: 613,48
            id:b213
            on_press: sequencer.monitor(b213)
        CustButton:
            pos: 660,48
            id:b214
            on_press: sequencer.monitor(b214)
        CustButton:
            pos: 707,48
            id:b215
            on_press: sequencer.monitor(b215)
        CustButton:
            pos: 754,48
            id:b216
            on_press: sequencer.monitor(b216)

        

        CustButton:
            pos: 49,95
            id:b301
            on_press: sequencer.monitor(b301)
        CustButton:
            pos: 96,95
            id:b302
            on_press: sequencer.monitor(b302)
        CustButton:
            pos: 143,95
            id:b303
            on_press: sequencer.monitor(b303)
        CustButton:
            pos: 190,95       
            id:b304
            on_press: sequencer.monitor(b304)
        CustButton:
            pos: 237,95
            id:b305
            on_press: sequencer.monitor(b305)
        CustButton:
            pos: 284,95
            id:b306
            on_press: sequencer.monitor(b306)
        CustButton:
            pos: 331,95
            id:b307
            on_press: sequencer.monitor(b307)
        CustButton:
            pos: 378,95
            id:b308
            on_press: sequencer.monitor(b308)
        CustButton:
            pos: 425,95
            id:b309
            on_press: sequencer.monitor(b309)
        CustButton:
            pos: 472,95
            id:b310
            on_press: sequencer.monitor(b310)
        CustButton:
            pos: 519,95
            id:b311
            on_press: sequencer.monitor(b311)
        CustButton:
            pos: 566,95
            id:b312
            on_press: sequencer.monitor(b312)
        CustButton:
            pos: 613,95
            id:b313
            on_press: sequencer.monitor(b313)
        CustButton:
            pos: 660,95
            id:b314
            on_press: sequencer.monitor(b314)
        CustButton:
            pos: 707,95
            id:b315
            on_press: sequencer.monitor(b315)
        CustButton:
            pos: 754,95
            id:b316
            on_press: sequencer.monitor(b316)


        CustButton:
            pos: 49,142
            id:b401
            on_press: sequencer.monitor(b401)
        CustButton:
            pos: 96,142
            id:b402
            on_press: sequencer.monitor(b402)
        CustButton:
            pos: 143,142
            id:b403
            on_press: sequencer.monitor(b403)
        CustButton:
            pos: 190,142
            id:b404
            on_press: sequencer.monitor(b404)
        CustButton:
            pos: 237,142
            id:b405
            on_press: sequencer.monitor(b405)
        CustButton:
            pos: 284,142
            id:b406
            on_press: sequencer.monitor(b406)
        CustButton:
            pos: 331,142
            id:b407
            on_press: sequencer.monitor(b407)
        CustButton:
            pos: 378,142
            id:b408
            on_press: sequencer.monitor(b408)
        CustButton:
            pos: 425,142
            id:b409
            on_press: sequencer.monitor(b409)
        CustButton:
            pos: 472,142
            id:b410
            on_press: sequencer.monitor(b410)
        CustButton:
            pos: 519,142
            id:b411
            on_press: sequencer.monitor(b411)
        CustButton:
            pos: 566,142
            id:b412
            on_press: sequencer.monitor(b412)
        CustButton:
            pos: 613,142
            id:b413
            on_press: sequencer.monitor(b413)
        CustButton:
            pos: 660,142
            id:b414
            on_press: sequencer.monitor(b414)
        CustButton:
            pos: 707,142
            id:b415
            on_press: sequencer.monitor(b415)
        CustButton:
            pos: 754,142
            id:b416
            on_press: sequencer.monitor(b416)



        CustButton:
            pos: 49,189
            id:b501
            on_press: sequencer.monitor(b501)
        CustButton:
            pos: 96,189
            id:b502
            on_press: sequencer.monitor(b502)
        CustButton:
            pos: 143,189
            id:b503
            on_press: sequencer.monitor(b503)
        CustButton:
            pos: 190,189
            id:b504
            on_press: sequencer.monitor(b504)
        CustButton:
            pos: 237,189
            id:b505
            on_press: sequencer.monitor(b505)
        CustButton:
            pos: 284,189
            id:b506
            on_press: sequencer.monitor(b506)
        CustButton:
            pos: 331,189
            id:b507
            on_press: sequencer.monitor(b507)
        CustButton:
            pos: 378,189
            id:b508
            on_press: sequencer.monitor(b508)
        CustButton:
            pos: 425,189
            id:b509
            on_press: sequencer.monitor(b509)
        CustButton:
            pos: 472,189
            id:b510
            on_press: sequencer.monitor(b510)
        CustButton:
            pos: 519,189
            id:b511
            on_press: sequencer.monitor(b511)
        CustButton:
            pos: 566,189
            id:b512
            on_press: sequencer.monitor(b512)
        CustButton:
            pos: 613,189
            id:b513
            on_press: sequencer.monitor(b513)
        CustButton:
            pos: 660,189
            id:b514
            on_press: sequencer.monitor(b514)
        CustButton:
            pos: 707,189
            id:b515
            on_press: sequencer.monitor(b515)
        CustButton:
            pos: 754,189
            id:b516
            on_press: sequencer.monitor(b516)





        CustButton:
            pos: 49,236
            id:b601
            on_press: sequencer.monitor(b601)
        CustButton:
            pos: 96,236
            id:b602
            on_press: sequencer.monitor(b602)
        CustButton:
            pos: 143,236
            id:b603
            on_press: sequencer.monitor(b603)
        CustButton:
            pos: 190,236
            id:b604
            on_press: sequencer.monitor(b604)
        CustButton:
            pos: 237,236
            id:b605
            on_press: sequencer.monitor(b605)
        CustButton:
            pos: 284,236
            id:b606
            on_press: sequencer.monitor(b606)
        CustButton:
            pos: 331,236
            id:b607
            on_press: sequencer.monitor(b607)
        CustButton:
            pos: 378,236
            id:b608
            on_press: sequencer.monitor(b608)
        CustButton:
            pos: 425,236
            id:b609
            on_press: sequencer.monitor(b609)
        CustButton:
            pos: 472,236
            id:b610
            on_press: sequencer.monitor(b610)
        CustButton:
            pos: 519,236
            id:b611
            on_press: sequencer.monitor(b611)
        CustButton:
            pos: 566,236
            id:b612
            on_press: sequencer.monitor(b612)
        CustButton:
            pos: 613,236
            id:b613
            on_press: sequencer.monitor(b613)
        CustButton:
            pos: 660,236
            id:b614
            on_press: sequencer.monitor(b614)
        CustButton:
            pos: 707,236
            id:b615
            on_press: sequencer.monitor(b615)
        CustButton:
            pos: 754,236
            id:b616
            on_press: sequencer.monitor(b616)


        CustButton:
            pos: 49,283
            id:b701
            on_press: sequencer.monitor(b701)
        CustButton:
            pos: 96,283
            id:b702
            on_press: sequencer.monitor(b702)
        CustButton:
            pos: 143,283
            id:b703
            on_press: sequencer.monitor(b703)
        CustButton:
            pos: 190,283
            id:b704
            on_press: sequencer.monitor(b704)
        CustButton:
            pos: 237,283
            id:b705
            on_press: sequencer.monitor(b705)
        CustButton:
            pos: 284,283
            id:b706
            on_press: sequencer.monitor(b706)
        CustButton:
            pos: 331,283
            id:b707
            on_press: sequencer.monitor(b707)
        CustButton:
            pos: 378,283
            id:b708
            on_press: sequencer.monitor(b708)
        CustButton:
            pos: 425,283
            id:b709
            on_press: sequencer.monitor(b709)
        CustButton:
            pos: 472,283
            id:b710
            on_press: sequencer.monitor(b710)
        CustButton:
            pos: 519,283
            id:b711
            on_press: sequencer.monitor(b711)
        CustButton:
            pos: 566,283
            id:b712
            on_press: sequencer.monitor(b712)
        CustButton:
            pos: 613,283
            id:b713
            on_press: sequencer.monitor(b713)
        CustButton:
            pos: 660,283
            id:b714
            on_press: sequencer.monitor(b714)
        CustButton:
            pos: 707,283
            id:b715
            on_press: sequencer.monitor(b715)
        CustButton:
            pos: 754,283
            id:b716
            on_press: sequencer.monitor(b716)

        CustButton:
            pos: 49,330
            id:b801
            on_press: sequencer.monitor(b801)
        CustButton:
            pos: 96,330
            id:b802
            on_press: sequencer.monitor(b802)
        CustButton:
            pos: 143,330
            id:b803
            on_press: sequencer.monitor(b803)
        CustButton:
            pos: 190,330
            id:b804
            on_press: sequencer.monitor(b804)
        CustButton:
            pos: 237,330
            id:b805
            on_press: sequencer.monitor(b805)
        CustButton:
            pos: 284,330
            id:b806
            on_press: sequencer.monitor(b806)
        CustButton:
            pos: 331,330
            id:b807
            on_press: sequencer.monitor(b807)
        CustButton:
            pos: 378,330
            id:b808
            on_press: sequencer.monitor(b808)
        CustButton:
            pos: 425,330
            id:b809
            on_press: sequencer.monitor(b809)
        CustButton:
            pos: 472,330
            id:b810
            on_press: sequencer.monitor(b810)
        CustButton:
            pos: 519,330
            id:b811
            on_press: sequencer.monitor(b811)
        CustButton:
            pos: 566,330
            id:b812
            on_press: sequencer.monitor(b812)
        CustButton:
            pos: 613,330
            id:b813
            on_press: sequencer.monitor(b813)
        CustButton:
            pos: 660,330
            id:b814
            on_press: sequencer.monitor(b814)
        CustButton:
            pos: 707,330
            id:b815
            on_press: sequencer.monitor(b815)
        CustButton:
            pos: 754,330
            id:b816
            on_press: sequencer.monitor(b816)







        CustButton3:
            pos: 49,377
            background_color: (.37, .39, .45, 0)
            id:b901
            text: "1"
        CustButton3:
            pos: 96,377
            background_color: (.37, .39, .45, 0)
            id:b902
            text: "."
        CustButton3:
            pos: 143,377
            background_color: (.37, .39, .45, 0)
            id:b903
            text: "."
        CustButton3:
            pos: 190,377
            background_color: (.37, .39, .45, 0)
            id:b904
            text: "."
        CustButton3:
            pos: 237,377
            background_color: (.37, .39, .45, 0)
            id:b905
            text: "2"
        CustButton3:
            pos: 284,377
            background_color: (.37, .39, .45, 0)
            id:b906
            text: "."
        CustButton3:
            pos: 331,377
            background_color: (.37, .39, .45, 0)
            id:b907
            text: "."
        CustButton3:
            pos: 378,377
            background_color: (.37, .39, .45, 0)
            id:b908
            text: "."
        CustButton3:
            pos: 425,377
            background_color: (.37, .39, .45, 0)
            id:b909
            text: "3"
        CustButton3:
            pos: 472,377
            background_color: (.37, .39, .45, 0)
            id:b910
            text: "."
        CustButton3:
            pos: 519,377
            background_color: (.37, .39, .45, 0)
            id:b911
            text: "."
        CustButton3:
            pos: 566,377
            background_color: (.37, .39, .45, 0)
            id:b912
            text: "."
        CustButton3:
            pos: 613,377
            background_color: (.37, .39, .45, 0)
            id:b913
            text: "4"
        CustButton3:
            pos: 660,377
            background_color: (.37, .39, .45, 0)
            id:b914
            text: "."
        CustButton3:
            pos: 707,377
            background_color: (.37, .39, .45, 0)
            id:b915
            text: "."
        CustButton3:
            pos: 754,377
            background_color: (.37, .39, .45, 0)
            id:b916
            text: "."


        CustButton3:
            id:b015
            pos: 50,0
            size: 15,415
            background_color: (.37, .39, .45, 1) 
            on_press: b015.state='normal'            
        CustButton2:
            pos: 1,1
            text: "C3"
            id:b100
            background_color: 255,255,255,0.8
            color: 0,0,0,1
        CustButton2:
            pos: 1,48
            text: "C#3"
            id:b200
            background_color: 0,0,0,0.7
        CustButton2:
            pos: 1,95
            text: "D3"
            id:b300
            background_color: 255,255,255,0.8
            color: 0,0,0,1
        CustButton2:
            pos: 1,142
            text: "D#3"
            id:b400
            background_color: 0,0,0,0.7
        CustButton2:
            pos: 1,189
            text: "E3"
            id:b500
            background_color: 255,255,255,0.8
            color: 0,0,0,1
        CustButton2:
            pos: 1,236
            text: "F3"
            id:b600
            background_color: 255,255,255,0.8
            color: 0,0,0,1
        CustButton2:
            pos: 1,283
            text: "F#3"
            id:b700
            background_color: 0,0,0,0.7
        CustButton2:
            pos: 1,330
            text: "G3"
            id:b800
            background_color: 255,255,255,0.8
            color: 0,0,0,1

        

        CustButton3:
            id:b017
            pos: 1000,1000
            size: 15,415
            background_color: (0.5, 0, 0, 1)
            on_press: b017.state='normal'

        CustButton3:
            id:b019
            pos: 1000,1000
            size: 15,415
            background_color: (.37, .39, .45, 1)  
        



        CustToggleButton:
            markup: True
            pos: 1,419
            size: 90, 60
            text: "%s"%(icon('icon-play', 22))
            id:b001
            on_press: sequencer.start()
        CustButton3:
            markup: True
            pos: 93,419
            size: 90, 60
            text: "%s"%(icon('icon-stop', 22))
            id:b002
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: sequencer.stop()
        CustToggleButton:
            pos: 185,419
            size: 60, 60
            id:b003
            text: "120"
            font_size: 27
            on_press:b004.state='normal'
            on_press:b020.state='normal'
            on_press:sequencer.mode(2)
            on_press:sequencer.closemenus()
        CustToggleButton:
            pos: 247,419
            size: 95, 60
            text: "4.0"
            id:b004
            font_size: 27
            on_press:b003.state='normal'
            on_press:b020.state='normal'
            on_press:sequencer.mode(3)
            on_press:sequencer.closemenus()
        CustToggleButton:
            pos: 344,419
            size: 150, 60
            text: "TOOLS"
            id:b005
            on_press: sequencer.tools()
        CustToggleButton:
            pos: 496,419
            size: 150, 60
            text: "SEQUENCE"
            id:b006
            on_press: sequencer.seqmode()
        CustToggleButton:
            pos: 648,419
            size: 150, 60
            text: "MENU"
            id:b007
            on_press: sequencer.menu()

        CustButton3:
            id:b010
            pos: 1000,0
            size: 1000,419
            background_color: 0,0,0,0
            on_press: sequencer.closemenus()


        CustButton3:
            pos: 648,900
            size: 150,60
            text: "SONG"
            id:b008
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.transition.direction='left'
            on_press:root.manager.current='song_mode'
            on_press: sequencer.clear()
            on_press: sequencer.closemenus()
            on_press: sequencer.leaving()
            


        CustButton3:
            pos: 648,900
            size: 150,60
            text: "PARAM"
            id:b009
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.current='param_mode'
            on_press: sequencer.closemenus()
            on_press: sequencer.leaving()

        CustButton3:
            markup: True
            pos: 344,900
            size: 150,60
            text: "LFO %s"%(icon('icon-lock', 22))
            id:b011
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: sequencer.closemenus()
            #on_press:root.manager.current='LFOScreen'
            #on_press: sequencer.leaving()  
        CustButton3:
            markup: True
            pos: 344,900
            size: 150,60
            text: "ADSR %s"%(icon('icon-lock', 22))
            id:b012
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: sequencer.closemenus()
            #on_press:root.manager.current='ADSRScreen'
            #on_press: sequencer.leaving()              

        CustButton3:
            pos: 496,900
            size: 150,60
            text: "CLEAR"
            id:b013
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: sequencer.clear()
            on_press: sequencer.closemenus()
            on_press: sequencer.clearsequence()

        CustButton3:
            pos: 496,900
            size: 150,60
            text: "LOAD"
            id:b014
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.current='LoadSeq'
            on_press: sequencer.closemenus()
            on_press: sequencer.leaving()

        CustButton3:
            pos: 496,900
            size: 150,60
            text: "SAVE"
            id:b016
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.current='SaveSeq'
            on_press: sequencer.closemenus()
            on_press: sequencer.leaving()

        CustToggleButton:
            pos: 496,900
            size: 150,60
            text: "ZOOM"
            id:b020
            font_size: 25
            font_name:"Calibri"
            on_press:b004.state='normal'
            on_press:b003.state='normal'
            background_color: .68,.68,.84,1
            on_press: sequencer.closemenus()
            on_press: sequencer.mode(1)


        CustToggleButton:
            pos: 496,900
            size: 150,60
            text: "REC OFF"
            id:b022
            font_size: 25
            font_name:"Calibri"
            on_press:b022.state='normal'
            background_color: .68,.68,.84,1
            on_press: sequencer.recordingbut()            
            on_press: sequencer.closemenus()




        CustButton3:
            markup: True
            pos: 22,970
            size: 5,30
            text: "%s"%(icon('icon-search', 22))
            id:b021
            font_size: 30
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: sequencer.mode(4)
            on_press: sequencer.closemenus()


<LFOScreen>:

    b001:b001
    b002:b002
    b003:b003
    b004:b004
    b005:b005
    b006:b006
    b007:b007
    b008:b008
    b009:b009
    b010:b010
    b011:b011
    b012:b012
    b013:b013
    b014:b014
    b016:b016
    b017:b017

    b019:b019
    b020:b020
    b021:b021
    b022:b022
    b023:b023
    b024:b024
    b025:b025
    l1:l1
    id:LFOScreen
    GridLayout:
        canvas.before:
           

            Color:
                rgba: (.37, .39, .45, 0.4)
            Rectangle:
                pos: self.pos
                size: self.size
            
            
        
        Widget:
            id:w_canvas
            pos:225,10
            canvas:

                Color:
                    rgba: (1, 1, 1, 0.4)
                Rectangle:
                    pos: self.pos
                    size: 2,380 
                Rectangle:
                    pos: (self.pos[0]+175, self.pos[1])
                    size: 2,380 
                Rectangle:
                    pos: (self.pos[0]+350, self.pos[1])
                    size: 2,380 
                Rectangle:
                    pos: (self.pos[0]+525, self.pos[1])
                    size: 2,380 
                Rectangle:
                    pos: (50,20 )
                    size: 700,2 
                Rectangle:
                    pos: (50,380 )
                    size: 700,2 
                Rectangle:
                    pos: (50,290 )
                    size: 700,2 
                Rectangle:
                    pos: (50,110 )
                    size: 700,2                     
                Color:
                    rgba:(1,1,1,1)
                Rectangle:
                    pos: (50,10)
                    size: 3,380 
                Rectangle:
                    pos: (20,200)
                    size: 760,3 
                Color:
                    rgba:(0, 0.7, 0, 1)
                Line:
                    group:'a'
                    points:[(52,15),(400,385)]
                    width:3
                Line:
                    group:'b'
                    points:[(400,385),(748,15)]
                    width:3
                Line:
                    group:'c'
                    ellipse:(-9310,15,710,710,90,180)
                    width:3
                Line:
                    group:'d'
                    ellipse:(952,-325,710,710,270,360)
                    width:3
                Line:
                    group:'e'
                    ellipse:(9400,15,668,755,180,270)
                    width:3
                Line:
                    group:'f'
                    ellipse:(982,-370,668,755,0,90)
                    width:3
                Ellipse:
                    group:'g'
                    size:(20,20)
                    pos:(300,300)

        Label:
            font_size:28
            text:'0'
            pos:-10,167
        Label:
            id:l1
            font_size:28
            text:'4'
            pos:715,167


        CustToggleButton:
            id:b025
            pos: 55,10
            size: 14,380
            background_color: .68,.68,.84,1
            text:'0'
            on_press: LFOScreen.mode(4)     
            on_press:  b023.state='normal'  
            on_press:  b024.state='normal'  
            on_press:  b003.state='normal'        
            on_press:  b004.state='normal'                                    
        CustToggleButton:
            id:b024
            pos: 17,370
            size: 70, 40
            text: "100"   
            on_press: LFOScreen.mode(5) 
            on_press:  b023.state='normal'  
            on_press:  b025.state='normal'  
            on_press:  b003.state='normal'        
            on_press:  b004.state='normal'                              
        CustToggleButton:
            pos: 1700,30
            size: 70, 40
            text: "rgt"
            on_press: LFOScreen.rgt()
        CustToggleButton:
            pos: 1700,80
            size: 70, 40
            text: "lft"            
            on_press: LFOScreen.lft()
        CustToggleButton:
            pos: 1600,30
            size: 70, 40
            text: "up"
            on_press: LFOScreen.up()
        CustToggleButton:
            pos: 1600,80
            size: 70, 40
            text: "dw"            
            on_press: LFOScreen.dw()
        CustToggleButton:
            pos: 1500,80
            size: 70, 40
            text: "strl"            
            on_press: LFOScreen.strl()
        CustToggleButton:
            pos: 1500,30
            size: 70, 40
            text: "strr"            
            on_press: LFOScreen.strr()                        
        CustToggleButton:
            id:b023
            pos: 600,80
            size: 40, 40       
            text:'X'     
            on_press: LFOScreen.mode(1)
            on_press:  b025.state='normal'  
            on_press:  b024.state='normal'  
            on_press:  b003.state='normal'        
            on_press:  b004.state='normal'               



        CustButton3:
            id:b017
            pos: 1000,1000
            size: 15,415
            background_color: (0.5, 0, 0, 1)
            on_press: b017.state='normal'

        CustButton3:
            id:b019
            pos: 1000,1000
            size: 15,415
            background_color: (.37, .39, .45, 1)  
        



        CustToggleButton:
            markup: True
            pos: 1,419
            size: 90, 60
            text: "%s"%(icon('icon-play', 22))
            id:b001
            on_press: LFOScreen.start()
        CustButton3:
            markup: True
            pos: 93,419
            size: 90, 60
            text: "%s"%(icon('icon-stop', 22))
            id:b002
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: LFOScreen.stop()
        CustToggleButton:
            pos: 185,419
            size: 60, 60
            id:b003
            text: "120"
            font_size: 27
            on_press:b004.state='normal'
            on_press:b020.state='normal'
            on_press:  b023.state='normal'  
            on_press:  b024.state='normal'  
            on_press:  b025.state='normal'                      
            on_press:LFOScreen.mode(2)
            on_press:LFOScreen.closemenus()
        CustToggleButton:
            pos: 247,419
            size: 95, 60
            text: "4.0"
            id:b004
            font_size: 27
            on_press:b003.state='normal'
            on_press:b020.state='normal'
            on_press:  b023.state='normal'  
            on_press:  b024.state='normal'  
            on_press:  b025.state='normal'             
            on_press:LFOScreen.mode(3)
            on_press:LFOScreen.closemenus()
        CustToggleButton:
            pos: 344,419
            size: 150, 60
            text: "TOOLS"
            id:b005
            on_press: LFOScreen.tools()
        CustToggleButton:
            pos: 496,419
            size: 150, 60
            text: "LFO"
            id:b006          
            on_press: LFOScreen.seqmode()
        CustToggleButton:
            pos: 648,419
            size: 150, 60
            text: "MENU"
            id:b007
            on_press: LFOScreen.menu()

        CustButton3:
            id:b010
            pos: 1000,0
            size: 1000,419
            background_color: 0,0,0,0
            on_press: LFOScreen.closemenus()


        CustButton3:
            pos: 648,900
            size: 150,60
            text: "SONG"
            id:b008
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.transition.direction='left'
            on_press:root.manager.current='song_mode'
            on_press: LFOScreen.closemenus()
            on_press: LFOScreen.leaving()
            


        CustButton3:
            pos: 648,900
            size: 150,60
            text: "PARAM"
            id:b009
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.current='param_mode'
            on_press: LFOScreen.closemenus()
            on_press: LFOScreen.leaving()

        CustButton3:
            markup: True
            pos: 344,900
            size: 150,60
            text: "SEQUENCE %s"%(icon('icon-lock', 22))
            id:b011
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: LFOScreen.closemenus()
            on_press:root.manager.current='piano_roll'
            on_press: LFOScreen.leaving()            

        CustButton3:
            markup: True
            pos: 344,900
            size: 150,60
            text: "ADSR %s"%(icon('icon-lock', 22))
            id:b012
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: LFOScreen.closemenus()
            on_press:root.manager.current='ADSRScreen'
            on_press: LFOScreen.leaving()            

        CustButton3:
            pos: 496,900
            size: 150,60
            text: "RESET"
            id:b013
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: LFOScreen.reset()
            on_press: LFOScreen.closemenus()


        CustButton3:
            pos: 496,900
            size: 150,60
            text: "LOAD"
            id:b014
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.current='LoadSeq'
            on_press: LFOScreen.closemenus()


        CustButton3:
            pos: 496,900
            size: 150,60
            text: "SAVE"
            id:b016
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.current='SaveSeq'
            on_press: LFOScreen.closemenus()


        CustToggleButton:
            pos: 496,900
            size: 150,60
            text: "ZOOM"
            id:b020
            font_size: 25
            font_name:"Calibri"
            on_press:b004.state='normal'
            on_press:b003.state='normal'
            background_color: .68,.68,.84,1
            on_press: LFOScreen.closemenus()
            on_press: LFOScreen.mode(1)


        CustToggleButton:
            pos: 496,900
            size: 150,60
            text: "REC OFF"
            id:b022
            font_size: 25
            font_name:"Calibri"
            on_press:b022.state='normal'
            background_color: .68,.68,.84,1
            on_press: LFOScreen.closemenus()
            on_press: LFOScreen.recording()



        CustButton3:
            markup: True
            pos: 22,970
            size: 5,30
            text: "%s"%(icon('icon-search', 22))
            id:b021
            font_size: 30
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: LFOScreen.mode(4)
            on_press: LFOScreen.closemenus()






<ADSRScreen>:

    b001:b001
    b002:b002
    b003:b003
    b004:b004
    b005:b005
    b006:b006
    b007:b007
    b008:b008
    b009:b009
    b010:b010
    b011:b011
    b012:b012
    b013:b013
    b014:b014
    b016:b016
    b017:b017

    b019:b019
    b020:b020
    b021:b021
    b022:b022
    b023:b023
    b024:b024
    b025:b025
    b026:b026
    b027:b027
    b028:b028
    l1:l1
    id:ADSRScreen
    GridLayout:
        canvas.before:
           

            Color:
                rgba: (.37, .39, .45, 0.4)
            Rectangle:
                pos: self.pos
                size: self.size
            
            
        
        Widget:
            id:w_canvas
            pos:225,10
            canvas:

                Color:
                    rgba: (1, 1, 1, 0.4)
                Rectangle:
                    pos: self.pos
                    size: 2,380 
                Rectangle:
                    pos: (self.pos[0]+175, self.pos[1])
                    size: 2,380 
                Rectangle:
                    pos: (self.pos[0]+350, self.pos[1])
                    size: 2,380 
                Rectangle:
                    pos: (self.pos[0]+525, self.pos[1])
                    size: 2,380 
                Rectangle:
                    pos: (50,200 )
                    size: 700,2 
                Rectangle:
                    pos: (50,380 )
                    size: 700,2 
                Rectangle:
                    pos: (50,290 )
                    size: 700,2 
                Rectangle:
                    pos: (50,110 )
                    size: 700,2                   
                Color:
                    rgba:(1,1,1,1)
                Rectangle:
                    pos: (50,10)
                    size: 3,380 
                Rectangle:
                    pos: (20,30)
                    size: 760,3 
                Color:
                    rgba:(0, 0.7, 0, 1)
                Line:
                    group:'a'
                    points:[(52,30),(100,385)]
                    width:3
                Line:
                    group:'b'
                    points:[(100,385),(150,300)]
                    width:3
                Line:
                    group:'c'
                    points:[(150,300),(300,300)]
                    width:3
                Line:
                    group:'d'
                    points:[(300,300),(500,30)]
                    width:3
                Ellipse:
                    group:'e'
                    size:(20,20)
                    pos:(300,300)
                Ellipse:
                    group:'f'
                    size:(20,20)
                    pos:(300,300)
                Ellipse:
                    group:'g'
                    size:(20,20)
                    pos:(300,300)  


        Label:
            font_size:28
            text:'0'
            pos:-10,-33
        Label:
            id:l1
            font_size:28
            text:'4'
            pos:715,-33


                                   
        CustToggleButton:
            id:b024
            pos: 17,370
            size: 70, 40
            text: "100"   
            on_press: ADSRScreen.mode(5) 
            on_press:  b023.state='normal'  
            on_press:  b025.state='normal'  
            on_press:  b003.state='normal'        
            on_press:  b004.state='normal'                              
        CustToggleButton:
            pos: 1700,130
            size: 70, 40
            text: "rgt"
            on_press: ADSRScreen.up2()
        CustToggleButton:
            pos: 1700,180
            size: 70, 40
            text: "lft"            
            on_press: ADSRScreen.dw2()
        CustToggleButton:
            pos: 1600,130
            size: 70, 40
            text: "up"
            on_press: ADSRScreen.up()
        CustToggleButton:
            pos: 1600,180
            size: 70, 40
            text: "dw"            
            on_press: ADSRScreen.dw()
        CustToggleButton:
            pos: 1500,180
            size: 70, 40
            text: "strl"            
            on_press: ADSRScreen.strlll()
        CustToggleButton:
            pos: 1500,130
            size: 70, 40
            text: "strr"            
            on_press: ADSRScreen.strrrr()                        
        CustToggleButton:
            id:b023
            pos: 600,13
            size: 40, 40       
            text:'X'     
            on_press: ADSRScreen.mode(1)
            on_press:  b025.state='normal'  
            on_press:  b024.state='normal'  
            on_press:  b003.state='normal'        
            on_press:  b004.state='normal'   
            on_press:  b026.state='normal' 
            on_press:  b027.state='normal' 
            on_press:  b028.state='normal'             
        CustToggleButton:
            id:b025
            pos: 200,13
            size: 40, 40       
            text:'X'     
            on_press: ADSRScreen.mode(4)
            on_press:  b023.state='normal'  
            on_press:  b024.state='normal'  
            on_press:  b003.state='normal'        
            on_press:  b004.state='normal'  
            on_press:  b026.state='normal' 
            on_press:  b027.state='normal' 
            on_press:  b028.state='normal'
        CustToggleButton:
            id:b026
            pos: 300,13
            size: 40, 40       
            text:'X'     
            on_press: ADSRScreen.mode(7)
            on_press:  b025.state='normal'  
            on_press:  b024.state='normal'  
            on_press:  b003.state='normal'        
            on_press:  b004.state='normal' 
            on_press:  b023.state='normal' 
            on_press:  b027.state='normal' 
            on_press:  b028.state='normal'             
        CustToggleButton:
            id:b027
            pos: 400,13
            size: 40, 40       
            text:'X'     
            on_press: ADSRScreen.mode(8)
            on_press:  b025.state='normal'  
            on_press:  b024.state='normal'  
            on_press:  b003.state='normal'        
            on_press:  b004.state='normal'
            on_press:  b026.state='normal' 
            on_press:  b023.state='normal' 
            on_press:  b028.state='normal'              
        CustToggleButton:
            id:b028
            pos: 17,180
            size: 70, 40
            text:'80'     
            on_press: ADSRScreen.mode(6)
            on_press:  b025.state='normal'  
            on_press:  b024.state='normal'  
            on_press:  b003.state='normal'        
            on_press:  b004.state='normal'  
            on_press:  b026.state='normal' 
            on_press:  b027.state='normal' 
            on_press:  b023.state='normal'            

        CustButton3:
            id:b017
            pos: 1000,1000
            size: 15,415
            background_color: (0.5, 0, 0, 1)
            on_press: b017.state='normal'

        CustButton3:
            id:b019
            pos: 1000,1000
            size: 15,415
            background_color: (.37, .39, .45, 1)  
        



        CustToggleButton:
            markup: True
            pos: 1,419
            size: 90, 60
            text: "%s"%(icon('icon-play', 22))
            id:b001
            on_press: ADSRScreen.start()
        CustButton3:
            markup: True
            pos: 93,419
            size: 90, 60
            text: "%s"%(icon('icon-stop', 22))
            id:b002
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: ADSRScreen.stop()
        CustToggleButton:
            pos: 185,419
            size: 60, 60
            id:b003
            text: "120"
            font_size: 27
            on_press:  b004.state='normal'
            on_press:  b023.state='normal'  
            on_press:  b024.state='normal'  
            on_press:  b025.state='normal'          
            on_press:  b026.state='normal' 
            on_press:  b027.state='normal' 
            on_press:  b028.state='normal'                                  
            on_press:ADSRScreen.mode(2)
            on_press:ADSRScreen.closemenus()
        CustToggleButton:
            pos: 247,419
            size: 95, 60
            text: "4.0"
            id:b004
            font_size: 27
            on_press:  b003.state='normal'
            on_press:  b023.state='normal'  
            on_press:  b024.state='normal'  
            on_press:  b025.state='normal'  
            on_press:  b026.state='normal' 
            on_press:  b027.state='normal' 
            on_press:  b028.state='normal'                        
            on_press:ADSRScreen.mode(3)
            on_press:ADSRScreen.closemenus()
        CustToggleButton:
            pos: 344,419
            size: 150, 60
            text: "TOOLS"
            id:b005
            on_press: ADSRScreen.tools()
        CustToggleButton:
            pos: 496,419
            size: 150, 60
            text: "ADSR"
            id:b006          
            on_press: ADSRScreen.seqmode()
        CustToggleButton:
            pos: 648,419
            size: 150, 60
            text: "MENU"
            id:b007
            on_press: ADSRScreen.menu()

        CustButton3:
            id:b010
            pos: 1000,0
            size: 1000,419
            background_color: 0,0,0,0
            on_press: ADSRScreen.closemenus()


        CustButton3:
            pos: 648,900
            size: 150,60
            text: "SONG"
            id:b008
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.transition.direction='left'
            on_press:root.manager.current='song_mode'
            on_press: ADSRScreen.closemenus()
            on_press: ADSRScreen.leaving()
            


        CustButton3:
            pos: 648,900
            size: 150,60
            text: "PARAM"
            id:b009
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.current='param_mode'
            on_press: ADSRScreen.closemenus()
            on_press: ADSRScreen.leaving()

        CustButton3:
            markup: True
            pos: 344,900
            size: 150,60
            text: "SEQUENCE %s"%(icon('icon-lock', 22))
            id:b011
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: ADSRScreen.closemenus()
            on_press:root.manager.current='piano_roll'
            on_press: ADSRScreen.leaving()            

        CustButton3:
            markup: True
            pos: 344,900
            size: 150,60
            text: "LFO %s"%(icon('icon-lock', 22))
            id:b012
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: ADSRScreen.closemenus()
            on_press:root.manager.current='LFOScreen'
            on_press: ADSRScreen.leaving()            

        CustButton3:
            pos: 496,900
            size: 150,60
            text: "RESET"
            id:b013
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: ADSRScreen.reset()
            on_press: ADSRScreen.closemenus()


        CustButton3:
            pos: 496,900
            size: 150,60
            text: "LOAD"
            id:b014
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.current='LoadSeq'
            on_press: ADSRScreen.closemenus()


        CustButton3:
            pos: 496,900
            size: 150,60
            text: "SAVE"
            id:b016
            font_size: 25
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press:root.manager.current='SaveSeq'
            on_press: ADSRScreen.closemenus()


        CustToggleButton:
            pos: 496,900
            size: 150,60
            text: "ZOOM"
            id:b020
            font_size: 25
            font_name:"Calibri"
            on_press:b004.state='normal'
            on_press:b003.state='normal'
            background_color: .68,.68,.84,1
            on_press: ADSRScreen.closemenus()
            on_press: ADSRScreen.mode(1)


        CustToggleButton:
            pos: 496,900
            size: 150,60
            text: "REC OFF"
            id:b022
            font_size: 25
            font_name:"Calibri"
            on_press:b022.state='normal'
            background_color: .68,.68,.84,1
            on_press: ADSRScreen.closemenus()
            on_press: ADSRScreen.recording()



        CustButton3:
            markup: True
            pos: 22,970
            size: 5,30
            text: "%s"%(icon('icon-search', 22))
            id:b021
            font_size: 30
            font_name:"Calibri"
            background_color: .68,.68,.84,1
            on_press: ADSRScreen.mode(4)
            on_press: ADSRScreen.closemenus()


<settings>:
    canvas.before:


        Color:
            rgba: (.37, .39, .45, 0.3)
        Rectangle:
            pos: self.pos
            size: self.size

            